---
title: "Missouri old-growth"
output: 
  html_document: 
    keep_md: true
---

```{r}
suppressPackageStartupMessages({
  library(raster)
  library(leaflet)
  library(leaflet.providers)
  library(leafpop)
  library(sf)
  library(tidyverse)
})
```
```{r photo geotags, echo=FALSE}
pic_files <- list.files(path = './Photos', pattern = '*.jpg|*.JPG|*.png|*.PNG', full.names = T)
exif <- exifr::read_exif(pic_files) %>% 
  dplyr::select(SourceFile, LON = GPSLongitude, LAT = GPSLatitude) %>% 
  mutate(SourceFile = paste0('https://github.com/jacobf37/Missouri_OldGrowth/blob/master/', str_remove(SourceFile, '[.]/'), '?raw=true')) %>% 
  as.data.frame()

```

```{r leaflet plot}
track <- read_sf(dsn = './assets', layer = 'Layer 3') %>% st_zm
nat_area <- read_sf(dsn = './assets', layer = 'MO_Natural_Areas') %>% 
  st_transform(4326)
track <- st_transform(track, 4326)
m <- leaflet() %>% setView(lng = -91.454, lat = 37.16, zoom = 14) %>% 
  addProviderTiles(provider = providers$Esri.WorldTopoMap) %>% 
  addPolygons(data = nat_area, color = 'green', fillColor = 'transparent') %>% 
  addPolygons(data = track$geometry, color = 'blue', fillColor = 'transparent') %>% 
  addMarkers(data = exif, lng = exif$LON, lat = exif$LAT, group = 'markers') %>% 
  addPopupImages(exif$SourceFile, height=200, group = 'markers')
m
```